name: GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'   # Runs daily at midnight
  workflow_dispatch:       # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate GitHub Snake
        uses: platane/snk@master
        with:
          color: '#FF69B4'          # Snake color (pink)
          background: '#0D1117'     # Background color (dark)
          github_token: ${{ secrets.GITHUB_TOKEN }}
